data:
  transform: hyperinv


inference:
  inference_runner: fse_inverter_inference_runner
  # editings_data: {"pap_smiling": [0, -4, -5, -6, -7, -8, -9, -10],
  #                 "pap_glasses": [0, 36, 37, 39, 40],
  #                 "age": [0, 5, 6, 7, 8, 9]
  #                 }
  editings_data: {"age": [-7, -5, -3, 3, 5, 7, 10],
              "fs_makeup": [5, 10, 15],
              "afro": [0.03, 0.07, 0.085, 0.1],
              "angry": [0.07, 0.1, 0.12],
              "purple_hair": [0.07, 0.1, 0.12],
              "glasses": [-7, 5],
              "face_roundness": [-17, -12, -8, 8, 12, 17], 
              "rotation": [-5.0, -3.0, -1.0, 1.0, 3.0, 5.0],
              "bobcut": [0.07, 0.12, 0.18],
              "bowlcut": [0.07, 0.14],
              "mohawk": [0.07, 0.10],
              "blond hair ": [-8, -4, 4, 8],
              "fs_smiling": [-9, -6, -3, 3, 6, 9]}


model:
  method: fse_inverter
  device: "0"
  batch_size: 8
